#!/bin/bash

workingdir="/opt/share"
port=8080
pidfile="/var/run/filesharer.pid"

getpid() {
	cat "$pidfile"
}

isrunning() {
	[ -f "$pidfile" ] && ps -p `getpid` &> /dev/null
}

start() {
	if isrunning; then
		echo "Service is already working"
	else
		echo "Starting filesharer service on port $port sharing content of $workingdir"
		cd "$workingdir"
		python3 -m http.server $port &> /dev/null &
		echo $! > "$pidfile"
	fi		
}

stop() {

	if ! isrunning ; then
		echo "Filesharer is not running"
	else
		echo "Stopping filesharer"
		kill $(getpid)
		sleep 1
		if isrunning; then
			echo "Service was not terminated, sending SIGKILL"
			kill -9 $(getpid)
		fi
		echo "Filesharer stopped"
	fi
	if [ -f $pidfile ]; then
		rm $pidfile
	fi
}

status() {
	if isrunning; then
		echo "Filesharer service is running with PID $(getpid)"
		echo "Sharing content of $workingdir on port $port"
	else
		echo "Filesharer is not running"
	fi
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        status
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac

exit 0
